### ISSUE TITLE
image size settings?

### ISSUE THREAD

**Issue by ghost** [proskur1n/pixelfish#1]
I really like this editor!! If there was an image size setting that'd be nice

**Comment by proskur1n** [comment]
Hello. I'm very glad you like this editor, even though I didn't expect anyone to use it. What do you mean by "image size setting"? There already a dialog for image size when creating a new image (Ctrl-N). Resizing existing images would require more work on the editor and I sadly don't have much time to work on it right now.

**Comment by ghost** [comment]
whoops! i didnt know there was a way to make new images
i think maybe ctrl-n is really obvious but i didnt think of it (I dont know if its in the readme)
i dont really need to adjust image settings after so its cool
nice project and goodbye!! sory this took me a while to check I don't use github much
